# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    file_path: %kernel.root_dir%/../web
    file_web_path: /uploads


services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    image.uploader:
        class: AppBundle\File\FileUploader
        arguments:
          - %file_path%%file_web_path%
          - %file_web_path%
